### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by luisgurmendez** [damikun/React-Toast#2]
- Regarding the interface that the ToastProvides has I recommend dropping the `push` prefix, so instead of `pushError` it would be just `error`.
 - It seems that having an undefined toast object doesn't make sense. So to avoid `toast?.` I recommend fixing that.
 - Importing font-awesome for just 4 icons seems like a heavy dependency to have.
 - To make custom Toast I recommend expecting a Toast component in the ToastProvider, this way the implementation isn't tied to any toast design.

**Comment by damikun** [comment]
Thx for all your inputs...

- I will fit types check of undefined..  thx for that I will add it to my to-do..
- FontAwesome is included because this toast is part of my UI lib which use FontAwesome in entire UI system... So I understand that it can be used over svg but this is not npm-package just custom implementation trimmed from my UI kit to be maybe helpful to someone..

Thx again for your notes.. Will add that prefix and null check to my to-do..
